Todo list
MuriloRoque/js_todo_list pull request #1
Opened 2020-06-24 10:59 UTC by MuriloRoque

## The look of the User Interface

When you open the app, you will see three buttons
- New Project: You can create a new Project
- New Todo: You can create a new Todo and Associate a project to it
- Show Project: A list of all Projects is displayed and the todo for each project with the edit and delete buttons

2020-06-24 12:52 UTC, maelfosso requested changes
# Changes required :red_circle:

Hello 

1. Please, as indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/projects_requirement.png), There should be `default` project.

2. Please Separate the DOM and the Logic as indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/modules_requirement.png)

3. Read the comments below

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-06-24 12:52 UTC, maelfosso commented on src/app/todos.js
> +};
Separate the logic from DOM manipulation.
- Remove the TODO class from there
- When removing a TODO for example, `values.splice` and `localStorage.setItem` are all logic. Kindly remove it from there
- Same thing for todoComplete, saving todo

2020-06-24 12:52 UTC, maelfosso commented on src/app/projects.js
> +export default projectForm;
Separate DOM manipulation from Logic. 
- Calling `projects.push` is Logic
- `localStorage.setItem` is Logic
The code between the two are DOM manipulation.  SEPARTE IT.

Kindly, read the comments left about TODO.

2020-06-24 12:58 UTC, MuriloRoque commented
Hello, @maelfosso thanks for the review. Just to clarify, we have a default project called "All Todos", do you want us to rename it to "Default"?

2020-06-24 15:20 UTC, Theophile-Kango commented
Dear TSE, here are some pictures that show the default Project when you first open the app
![default-project](https://user-images.githubusercontent.com/49276315/85583787-d8d09f80-b63e-11ea-89dc-d28d79d5d2d2.png)
![default-project-todo](https://user-images.githubusercontent.com/49276315/85583841-e6862500-b63e-11ea-868c-1f7a546cec92.png)
We made the required changes

2020-06-24 18:06 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED

Hi @MuriloRoque @Theophile-Kango good job team, kudos for  making all that corrections, however when I try to edit a Todo a new todo is created also leaving the old one in place this is not the desired behaviour, please look into that  :slightly_smiling_face: 

Please make changes and **request for another review** :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask:

2020-06-24 19:03 UTC, MuriloRoque commented
Hello there, thank you for noticing that bug, it slipped! :sweat_smile: 
I am looking forward to learning how to use testing in Javascript, so we are able to notice the mistakes easily.
We just made the required changes!

2020-06-25 00:08 UTC, bellom approved these changes
## Hi Team 👏 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-06-25 04:33 UTC, merged